server:
  port: 8846
spring:
  application:
    name: auth-service
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      server-addr: 192.168.150.101:8848
      discovery:
        namespace: 0196a48b-5ba6-4544-ace2-cec9e2da72ca
security:
  oauth2:
    client:
      client-id: learning
      client-secret: learning
      authorized-grant-types: password
      access-token-validity-seconds: 864000
      scope: all
    authorization:
      check-token-access: permitAll()
      token-key-access: permitAll()
      jwt:
        key-store: classpath:jwt.jks
        key-store-password: learning
        key-alias: jwt