server:
  port: 9420
spring:
  application:
    name: aichat-service
  cloud:
    nacos:
      server-addr: 192.168.150.101:8848
      discovery:
        namespace: 0196a48b-5ba6-4544-ace2-cec9e2da72ca

# 阿里云 DashScope 配置
aliyun:
  dashscope:
    app-id: "6a3d9d1c86a64f9486ec3ea5e2277af2" # !!! 在这里或 Config Server 中配置你的百炼应用 ID
    # 线程池配置 (可以根据需要调整)
    threadpool:
      core-size: 2
      max-size: 10 # 适当增加最大线程数以应对并发
      keep-alive-seconds: 60
      queue-capacity: 50 # 适当增加队列容量
