server:
  port: 8410
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost/learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 147258
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  cloud:
    nacos:
        server-addr: 192.168.150.101:8848
        discovery:
          namespace: 0196a48b-5ba6-4544-ace2-cec9e2da72ca

mybatis:
  mapper-locations: classpath:mapper/*.xml