server:
  port: 8430
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      server-addr: 192.168.150.101:8848
      discovery:
        namespace: 0196a48b-5ba6-4544-ace2-cec9e2da72ca
minio:
  endpoint: http://192.168.150.101:9000
  access-key: minioadmin
  secret-key: minioadmin
  video-bucket-name: videos
  cover-picture-bucket-name: cover-pictures
  profile-picture-bucket-name: profile-pictures
  certificate-picture-bucket-name: certificate-pictures
  roadmap-picture-bucket-name: roadmap-pictures
gateway:
  address: http://localhost:8080