# 网关服务基础配置
server:
  port: 8080  # 网关服务监听端口

spring:
  application:
    name: gateway  # 服务名称
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: localhost:8846/oauth/key  # JWT密钥集地址，用于令牌验证
  cloud:
    nacos:
      server-addr: 192.168.150.101:8848  # Nacos配置中心服务地址
      discovery:
        namespace: 0196a48b-5ba6-4544-ace2-cec9e2da72ca  # Nacos命名空间ID
    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现路由定位
      default-filters:
        - StripPrefix=1  # 默认移除路径前缀（去掉第一个斜杠后的部分）
      globalcors:
        #当设置为 true 时，全局 CORS 配置会覆盖所有 URL 路径（包括非网关路由的请求），例如 /actuator/** 或静态资源路径。
        #当设置为 false 时，全局 CORS 配置仅对通过网关路由（routes 中定义的路径）生效，而其他非路由路径（如直接访问 / 的静态页面）可能不会应用 CORS 配置。
        add-to-simple-url-handler-mapping: true  # 全局CORS配置
        cors-configurations:
          '[/**]':
            allowedOrigins: http://localhost:3000  # 允许的跨域来源
            allowedHeaders: Content-Type, Authorization  # 允许的请求头
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS  # 允许的HTTP方法

      routes:  # 路由规则定义
        - id: auth-service  # 认证服务路由
          uri: lb://auth-service  # 负载均衡指向auth-service  lb是LoadBalancer 的缩写
          predicates:
            - Path=/api/oauth/**  # 匹配/oauth开头的路径

        - id: user-service  # 用户服务路由
          uri: lb://user-service
          predicates:
            - name: Path #路径参数匹配
              args:
              - /api/users/**  # 匹配/users路径
              - /api/roles/**  # 匹配/roles路径

        - id: course-service  # 课程服务路由
          uri: lb://course-service
          predicates:
            - name: Path
              args:
                - /api/courses/**  # 课程相关路径
                - /api/categories/**  # 分类相关路径
                - /api/chapters/**  # 章节相关路径
                - /api/questions/**  # 题目相关路径
                - /api/answers/**  # 答案相关路径
                - /api/notes/**  # 笔记相关路径
                - /api/evaluations/**  # 评价相关路径

        - id: trade-service  # 交易服务路由
          uri: lb://trade-service
          predicates:
            - name: Path
              args:
                - /api/orders/**  # 订单相关路径
                - /api/payments/**  # 支付相关路径

        - id: file-service  # 文件服务路由
          uri: lb://file-service
          predicates:
            - name: Path
              args:
                - /api/videos/**  # 视频文件路径
                - /api/cover-pictures/**  # 封面图片路径
                - /api/profile-pictures/**  # 头像图片路径
                -
        - id: aichat-service # 智能聊天服务路由
          uri: lb://aichat-service
          predicates:
            - name: Path
              args:
                - /api/chat/**
        - id: dfs  # 分布式文件系统路由
          uri: http://192.168.150.101:9000  # 直接指向MinIO等存储服务
          predicates:
            - name: Path
              args:
                - /dfs/videos/**  # 视频存储访问路径
                - /dfs/cover-pictures/**  # 封面存储访问路径
                - /dfs/profile-pictures/**  # 头像存储访问路径