server:
  port: 8420
spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://localhost/learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 147258
  redis:
    host: 192.168.150.101
    port: 6379
    database: 0
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  cloud:
    nacos:
      server-addr: 192.168.150.101:8848
      discovery:
        namespace: 0196a48b-5ba6-4544-ace2-cec9e2da72ca
#    # 新增 Elasticsearch 配置
  elasticsearch:
    uris: http://192.168.150.101:9200
#      # 如果你的 Elasticsearch 设置了用户名和密码，也需要在这里配置：
#      # username: your_username
#      # password: your_password
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  page-size-zero: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
